version: '3.9'
services:
  nginxwebdav:
    container_name: nginxwebdav
    image: dgraziotin/nginx-webdav-nononsense
    volumes:
      - ./data:/data
      - ./nginx.conf:/etc/nginx/nginx.conf
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - VIRTUAL_HOST=webdav.bjornf.dev
      - LETSENCRYPT_HOST=webdav.bjornf.dev
      - VIRTUAL_PORT=80
      - WEBDAV_USERNAME=
      - WEBDAV_PASSWORD=
      - SERVER_NAMES=localhost,bjornf.dev
      - TIMEOUTS_S=1200 # these are seconds
      - CLIENT_MAX_BODY_SIZE=120M # must end with M(egabytes) or G(igabytes)
    ports:
      - 32080:80
    expose:
      - 80
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
